# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aLFUOxI2LE17FXt-TXYFclLDOut78MnF
"""

class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

    def saludar(self):
        print(f"Hola, mi nombre es {self.nombre} y tengo {self.edad} años.")

# Crear una instancia de la clase Persona
persona1 = Persona("Juan", 25)

# Acceder a los atributos de la instancia
print(persona1.nombre)  # Output: Juan
print(persona1.edad)  # Output: 25

# Llamar a un método de la instancia
persona1.saludar()  # Output: Hola, mi nombre es Juan y tengo 25 años.